import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, PromiseCard } from "@/components/ui";
import { getRepresentative, getRepresentativePromises } from "@/lib/data";

export default async function RepresentativeDetail({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const representative=getRepresentative(slug);if(!representative)notFound();const records=getRepresentativePromises(slug);const average=records.length?Math.round(records.reduce((sum,item)=>sum+item.progress,0)/records.length):0;
  return <div className="page narrow representative-detail"><Breadcrumbs items={[{label:"My Area",href:"/my-area"},{label:"Representatives",href:"/representatives"},{label:representative.name}]}/><section className="official-header"><div className={`portrait large level-${representative.level.toLowerCase()}`} aria-hidden="true"><span>{representative.initials}</span></div><div><span className="kicker">{representative.level} government · {representative.role}</span><h1>{representative.name}</h1><p>{representative.jurisdiction}</p><div className="official-meta"><span>{representative.party}</span><span>{representative.term}</span><span>{records.length} promises tracked</span></div></div></section><div className="detail-grid"><main><section className="official-summary"><div><span>Average documented progress</span><strong>{average}%</strong></div><div className="summary-bar"><i style={{width:`${average}%`}}/></div><p>This figure summarises the documented commitments below. It is not a general score of the office holder.</p></section><section className="subsection"><div className="section-heading"><div><span className="kicker">Public commitments</span><h2>Promises and status</h2></div></div>{records.length?<div className="stack">{records.map(item=><PromiseCard key={item.slug} promise={item}/>)}</div>:<div className="empty"><strong>No attributable promise has been verified yet.</strong><p>CivicLedger will show a record here when a specific, sourced commitment is reviewed.</p></div>}</section></main><aside className="panel facts"><h3>Office record</h3><dl><dt>Office</dt><dd>{representative.role}</dd><dt>Jurisdiction</dt><dd>{representative.jurisdiction}</dd><dt>Term</dt><dd>{representative.term}</dd><dt>What this office controls</dt><dd>{representative.responsibility}</dd><dt>Commitments assessed as</dt><dd>{representative.commitmentType}</dd></dl>{representative.pairedWith&&<Link className="paired-link" href={`/representatives/${representative.pairedWith}`}>View joint-ticket counterpart →</Link>}</aside></div></div>
}
