import { notFound } from "next/navigation";
import Link from "next/link";
import { getPromise, projects, getRepresentative } from "@/lib/data";
import { Breadcrumbs, Confidence, Progress, ProjectCard, StatusPill } from "@/components/ui";
export default async function PromiseDetail({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const p=getPromise(slug); if(!p)notFound();
  const connected=projects.filter(x=>p.projectSlugs.includes(x.slug));
  return <div className="page narrow"><Breadcrumbs items={[{label:"Promises",href:"/promises"},{label:p.title}]}/><div className="detail-head"><span className="kicker">{p.sector} · {p.level} government</span><h1>{p.title}</h1><div className="detail-meta"><StatusPill status={p.status}/><Confidence value={p.confidence}/><span>Demo updated {p.updated}</span></div></div>
    <blockquote><strong>{p.origin==="sourced"?"Sourced commitment · paraphrased":"Simulated campaign commitment"}</strong><p>{p.quote}</p><cite>{p.source}{p.sourceUrl&&<> · <a href={p.sourceUrl} target="_blank" rel="noopener noreferrer">Original source ↗</a></>}</cite></blockquote>
    <div className="detail-grid"><div><section className="panel"><h2>Why CivicLedger says this</h2><p className="lead">{p.why}</p><Progress value={p.progress}/><p className="note">All statuses and progress figures on this demo are simulated, including those attached to sourced commitments.</p>{p.target&&<><h3>Delivery target</h3><p>{p.target}</p></>}</section>
    {p.change&&<section className="panel change"><span className="kicker">Simulated change</span><h2>How the promise changed</h2><dl><dt>Original target</dt><dd>{p.change.previous}</dd><dt>Updated target</dt><dd>{p.change.current}</dd><dt>Reason</dt><dd>{p.change.reason}</dd><dt>Effective date</dt><dd>{p.change.date}</dd><dt>Supporting record</dt><dd>{p.change.source}</dd></dl></section>}
    <section className="subsection"><h2>Connected demo projects</h2>{connected.length?<><p className="note">Project progress and evidence descriptions are illustrative, not independently verified.</p><div className="stack">{connected.map(x=><ProjectCard key={x.slug} project={x}/>)}</div></>:<div className="empty"><strong>No linked project in this scenario.</strong><p>A campaign commitment is not proof of implementation.</p></div>}</section></div>
    <aside className="panel facts"><h3>Promise record</h3><dl><dt>Responsible office</dt><dd>{p.leader}</dd><dt>Government level</dt><dd>{p.level}</dd><dt>Sector</dt><dd>{p.sector}</dd><dt>Location</dt><dd>{p.location}</dd><dt>Record origin</dt><dd>{p.origin==="sourced"?"Public manifesto commitment; simulated assessment":"Simulated commitment and assessment"}</dd></dl><h3>Official profiles</h3>{p.officialSlugs.map(slug=><p key={slug}><Link href={`/representatives/${slug}`}>{getRepresentative(slug)?.role} →</Link></p>)}</aside></div></div>
}
