export type Status = "Completed" | "In Progress" | "Not Started" | "Modified" | "Broken / Abandoned" | "Insufficient Evidence";
export type Confidence = "High" | "Medium" | "Low" | "Unrated";
export type Evidence = { id:string; type:string; title:string; publisher:string; date:string; url:string; excerpt:string };
export type Project = { slug:string; name:string; description:string; location:string; status:Status; promiseSlug?:string; unpromised?:boolean; progress:number; budget?:string; fundedBy:string; implementedBy:string; contractor?:string; evidence:Evidence[] };
export type PromiseRecord = { slug:string; title:string; quote:string; source:string; sourceUrl:string; published:string; sector:string; level:string; leader:string; location:string; status:Status; confidence:Confidence; progress:number; updated:string; why:string; projectSlugs:string[]; change?:{previous:string;current:string;reason:string;date:string;source:string} };

export const leaders = [
  {role:"President",name:"Bola Ahmed Tinubu",level:"Federal",responsibility:"Federal policy and federally funded projects"},
  {role:"Governor",name:"Siminalayi Fubara",level:"State",responsibility:"Rivers State programmes and agencies"},
  {role:"LGA Chairman",name:"Ezebunwo Ichemati",level:"Local",responsibility:"Port Harcourt City local services"}
];

export const projects: Project[] = [
  {slug:"port-harcourt-ring-road",name:"Port Harcourt Ring Road",description:"A multi-junction road project intended to improve movement around greater Port Harcourt.",location:"Port Harcourt and adjoining LGAs",status:"In Progress",promiseSlug:"complete-ring-road",progress:46,budget:"₦195.3bn reported contract value",fundedBy:"Rivers State Government",implementedBy:"Rivers State Ministry of Works",contractor:"Julius Berger Nigeria Plc",evidence:[{id:"e1",type:"Government update",title:"Construction progress update",publisher:"Rivers State Government",date:"2025-05-12",url:"https://www.riversstate.gov.ng/",excerpt:"The state reported active construction across multiple sections of the route."},{id:"e2",type:"Independent reporting",title:"Ring road construction enters new phase",publisher:"The Guardian Nigeria",date:"2025-06-03",url:"https://guardian.ng/",excerpt:"Reporting documented ongoing works and the stated delivery timeline."}]},
  {slug:"primary-health-centre-upgrade",name:"Orogbum Primary Health Centre Upgrade",description:"Rehabilitation and equipment upgrade for a community primary healthcare facility.",location:"Orogbum, Port Harcourt City",status:"Completed",promiseSlug:"upgrade-primary-healthcare",progress:100,budget:"Not publicly itemised",fundedBy:"Rivers State Government",implementedBy:"Rivers State Primary Health Care Management Board",evidence:[{id:"e3",type:"Government document",title:"PHC rehabilitation programme update",publisher:"RSPHCMB",date:"2025-02-18",url:"https://www.riversstate.gov.ng/",excerpt:"The facility was listed among completed rehabilitation works."},{id:"e4",type:"Field evidence",title:"Community verification photographs",publisher:"CivicLedger reviewer",date:"2025-03-01",url:"#community-evidence",excerpt:"Dated photographs show the renovated exterior and clinical rooms in use."}]},
  {slug:"waterfront-drainage-repair",name:"Diobu Waterfront Drainage Repair",description:"Drainage clearance and targeted repairs intended to reduce seasonal flooding.",location:"Diobu, Port Harcourt City",status:"Insufficient Evidence",progress:20,unpromised:true,budget:"Not available",fundedBy:"Port Harcourt City LGA",implementedBy:"Port Harcourt City Works Department",evidence:[{id:"e5",type:"Government update",title:"Local drainage intervention notice",publisher:"Port Harcourt City LGA",date:"2025-04-07",url:"https://www.riversstate.gov.ng/",excerpt:"A public notice announced drainage works but did not provide completion evidence."}]}
];

export const promises: PromiseRecord[] = [
 {slug:"complete-ring-road",title:"Complete the Port Harcourt Ring Road",quote:"We will deliver the Port Harcourt Ring Road to unlock communities and reduce congestion.",source:"Rivers State policy address",sourceUrl:"https://www.riversstate.gov.ng/",published:"2024-01-29",sector:"Infrastructure",level:"State",leader:"Siminalayi Fubara",location:"Greater Port Harcourt",status:"In Progress",confidence:"High",progress:46,updated:"2026-09-12",why:"Construction is visible across multiple sections and is supported by both state updates and independent reporting. The road is not yet open end-to-end.",projectSlugs:["port-harcourt-ring-road"]},
 {slug:"upgrade-primary-healthcare",title:"Upgrade primary healthcare facilities",quote:"Primary healthcare centres will be rehabilitated and equipped to bring quality care closer to communities.",source:"Rivers State health programme briefing",sourceUrl:"https://www.riversstate.gov.ng/",published:"2024-03-14",sector:"Healthcare",level:"State",leader:"Siminalayi Fubara",location:"Rivers State",status:"Modified",confidence:"Medium",progress:64,updated:"2026-09-10",why:"Several facilities show credible completion evidence, but the programme target and timeline were revised and public facility-level reporting remains incomplete.",projectSlugs:["primary-health-centre-upgrade"],change:{previous:"Upgrade all targeted PHCs within the 2024 programme year.",current:"Deliver upgrades in phases through 2025–2026.",reason:"The implementing programme was publicly moved to phased delivery.",date:"2025-01-22",source:"Rivers State health programme update"}},
 {slug:"rehabilitate-public-schools",title:"Rehabilitate public primary schools",quote:"We will renew learning environments in public schools across the state.",source:"Education policy statement",sourceUrl:"https://www.riversstate.gov.ng/",published:"2024-02-10",sector:"Education",level:"State",leader:"Siminalayi Fubara",location:"Port Harcourt City",status:"Insufficient Evidence",confidence:"Low",progress:10,updated:"2026-09-08",why:"The commitment is documented, but CivicLedger has not found sufficiently specific project records or independent evidence for Port Harcourt City.",projectSlugs:[]}
];

export function getPromise(slug:string){return promises.find(p=>p.slug===slug)}
export function getProject(slug:string){return projects.find(p=>p.slug===slug)}
export function statusClass(status:Status){return "status "+status.toLowerCase().replaceAll(" ","-").replaceAll("/","")}
