import type { PromiseRecord, Status } from "./data";

// Illustrative commitments, not statements attributable to real office holders.
export const demoPromises: PromiseRecord[] = [
  {
    "slug": "federal-primary-care",
    "title": "Strengthen primary healthcare access",
    "quote": "Strengthen primary healthcare access",
    "sector": "Healthcare",
    "status": "In Progress",
    "progress": 62,
    "target": "Equip 100 facilities in the simulated pilot.",
    "officialSlugs": [
      "president",
      "vice-president"
    ],
    "level": "Federal",
    "leader": "Federal joint ticket",
    "location": "Nigeria",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "federal-affordable-housing",
    "title": "Expand affordable housing access",
    "quote": "Expand affordable housing access",
    "sector": "Infrastructure",
    "status": "Modified",
    "progress": 45,
    "target": "Revised pilot: 8 states instead of 12.",
    "officialSlugs": [
      "president",
      "vice-president"
    ],
    "level": "Federal",
    "leader": "Federal joint ticket",
    "location": "Nigeria",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": [],
    "change": {
      "previous": "Original simulated scope",
      "current": "Revised pilot: 8 states instead of 12.",
      "reason": "Illustrative scope revision for the demo.",
      "date": "2026-06-01",
      "source": "Simulated change record"
    }
  },
  {
    "slug": "federal-digital-skills",
    "title": "Launch a national digital-skills programme",
    "quote": "Launch a national digital-skills programme",
    "sector": "Education",
    "status": "Completed",
    "progress": 100,
    "target": "Train 5,000 young people in the demo scenario.",
    "officialSlugs": [
      "president",
      "vice-president"
    ],
    "level": "Federal",
    "leader": "Federal joint ticket",
    "location": "Nigeria",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "federal-school-connectivity",
    "title": "Connect public schools to reliable internet",
    "quote": "Connect public schools to reliable internet",
    "sector": "Education",
    "status": "Not Started",
    "progress": 0,
    "target": "Connect 250 schools in the demo scenario.",
    "officialSlugs": [
      "president",
      "vice-president"
    ],
    "level": "Federal",
    "leader": "Federal joint ticket",
    "location": "Nigeria",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "rivers-classroom-renewal",
    "title": "Deliver new classrooms and learning materials",
    "quote": "Deliver new classrooms and learning materials",
    "sector": "Education",
    "status": "Completed",
    "progress": 100,
    "target": "Renovate 20 classrooms in the demo scenario.",
    "officialSlugs": [
      "rivers-governor",
      "rivers-deputy-governor"
    ],
    "level": "State",
    "leader": "Rivers State joint ticket",
    "location": "Rivers State",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "rivers-maternal-care",
    "title": "Expand maternal and child healthcare",
    "quote": "Expand maternal and child healthcare",
    "sector": "Healthcare",
    "status": "In Progress",
    "progress": 72,
    "target": "Extend services at 10 facilities in the demo scenario.",
    "officialSlugs": [
      "rivers-governor",
      "rivers-deputy-governor"
    ],
    "level": "State",
    "leader": "Rivers State joint ticket",
    "location": "Rivers State",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "rivers-road-maintenance",
    "title": "Publish a transparent road-maintenance schedule",
    "quote": "Publish a transparent road-maintenance schedule",
    "sector": "Infrastructure",
    "status": "Not Started",
    "progress": 0,
    "target": "Publish a schedule covering 15 priority routes.",
    "officialSlugs": [
      "rivers-governor",
      "rivers-deputy-governor"
    ],
    "level": "State",
    "leader": "Rivers State joint ticket",
    "location": "Rivers State",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "senate-scholarships",
    "title": "Support district scholarships",
    "quote": "Support district scholarships",
    "sector": "Education",
    "status": "Completed",
    "progress": 100,
    "target": "Support 200 students in the demo scenario.",
    "officialSlugs": [
      "rivers-east-senator"
    ],
    "level": "Federal",
    "leader": "Rivers East Senate office",
    "location": "Rivers East",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "senate-health-oversight",
    "title": "Push for public reporting of health allocations",
    "quote": "Push for public reporting of health allocations",
    "sector": "Healthcare",
    "status": "In Progress",
    "progress": 55,
    "target": "Introduce an oversight motion and track three reporting milestones.",
    "officialSlugs": [
      "rivers-east-senator"
    ],
    "level": "Federal",
    "leader": "Rivers East Senate office",
    "location": "Rivers East",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "senate-flood-response",
    "title": "Advocate for coordinated flood response",
    "quote": "Advocate for coordinated flood response",
    "sector": "Infrastructure",
    "status": "Not Started",
    "progress": 0,
    "target": "Raise a motion and obtain an agency response; not execute construction.",
    "officialSlugs": [
      "rivers-east-senator"
    ],
    "level": "Federal",
    "leader": "Rivers East Senate office",
    "location": "Rivers East",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "house-bursaries",
    "title": "Support education bursaries",
    "quote": "Support education bursaries",
    "sector": "Education",
    "status": "Completed",
    "progress": 100,
    "target": "Support 150 students in the demo scenario.",
    "officialSlugs": [
      "ph-federal-representative"
    ],
    "level": "Federal",
    "leader": "Port Harcourt constituency office",
    "location": "Port Harcourt Federal Constituency II",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "house-health-outreach",
    "title": "Facilitate community health outreach",
    "quote": "Facilitate community health outreach",
    "sector": "Healthcare",
    "status": "In Progress",
    "progress": 67,
    "target": "Facilitate six outreach sessions with implementing partners.",
    "officialSlugs": [
      "ph-federal-representative"
    ],
    "level": "Federal",
    "leader": "Port Harcourt constituency office",
    "location": "Port Harcourt Federal Constituency II",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "house-road-advocacy",
    "title": "Advocate for priority road repairs",
    "quote": "Advocate for priority road repairs",
    "sector": "Infrastructure",
    "status": "Modified",
    "progress": 30,
    "target": "Secure agency correspondence on two priority roads.",
    "officialSlugs": [
      "ph-federal-representative"
    ],
    "level": "Federal",
    "leader": "Port Harcourt constituency office",
    "location": "Port Harcourt Federal Constituency II",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": [],
    "change": {
      "previous": "Original simulated scope",
      "current": "Secure agency correspondence on two priority roads.",
      "reason": "Illustrative scope revision for the demo.",
      "date": "2026-06-01",
      "source": "Simulated change record"
    }
  },
  {
    "slug": "assembly-school-inspections",
    "title": "Publish school oversight findings",
    "quote": "Publish school oversight findings",
    "sector": "Education",
    "status": "Completed",
    "progress": 100,
    "target": "Inspect eight schools and publish an oversight report.",
    "officialSlugs": [
      "ph-state-assembly"
    ],
    "level": "State",
    "leader": "Demo State Assembly representative",
    "location": "Port Harcourt State Constituency II",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "assembly-clinic-oversight",
    "title": "Track constituency clinic allocations",
    "quote": "Track constituency clinic allocations",
    "sector": "Healthcare",
    "status": "In Progress",
    "progress": 48,
    "target": "Review four allocations through legislative hearings.",
    "officialSlugs": [
      "ph-state-assembly"
    ],
    "level": "State",
    "leader": "Demo State Assembly representative",
    "location": "Port Harcourt State Constituency II",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "assembly-accessibility",
    "title": "Sponsor an accessibility bill",
    "quote": "Sponsor an accessibility bill",
    "sector": "Infrastructure",
    "status": "Not Started",
    "progress": 0,
    "target": "Track introduction, committee review and passage; not physical works.",
    "officialSlugs": [
      "ph-state-assembly"
    ],
    "level": "State",
    "leader": "Demo State Assembly representative",
    "location": "Port Harcourt State Constituency II",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "assembly-town-halls",
    "title": "Hold quarterly constituency town halls",
    "quote": "Hold quarterly constituency town halls",
    "sector": "Education",
    "status": "Insufficient Evidence",
    "progress": 0,
    "target": "Document four meetings with attendance and published minutes.",
    "officialSlugs": [
      "ph-state-assembly"
    ],
    "level": "State",
    "leader": "Demo State Assembly representative",
    "location": "Port Harcourt State Constituency II",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "local-market-sanitation",
    "title": "Improve market sanitation and waste collection",
    "quote": "Improve market sanitation and waste collection",
    "sector": "Healthcare",
    "status": "Completed",
    "progress": 100,
    "target": "Service 30 waste-collection points on a published schedule.",
    "officialSlugs": [
      "ph-chairman",
      "ph-vice-chairman"
    ],
    "level": "Local",
    "leader": "Port Harcourt City joint ticket",
    "location": "Port Harcourt City LGA",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "local-school-repairs",
    "title": "Repair local primary school facilities",
    "quote": "Repair local primary school facilities",
    "sector": "Education",
    "status": "In Progress",
    "progress": 60,
    "target": "Repair facilities in five schools in the demo scenario.",
    "officialSlugs": [
      "ph-chairman",
      "ph-vice-chairman"
    ],
    "level": "Local",
    "leader": "Port Harcourt City joint ticket",
    "location": "Port Harcourt City LGA",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "local-street-lights",
    "title": "Restore priority street lighting",
    "quote": "Restore priority street lighting",
    "sector": "Infrastructure",
    "status": "Broken / Abandoned",
    "progress": 25,
    "target": "Restore 40 lights; the simulated delivery window has expired.",
    "officialSlugs": [
      "ph-chairman",
      "ph-vice-chairman"
    ],
    "level": "Local",
    "leader": "Port Harcourt City joint ticket",
    "location": "Port Harcourt City LGA",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "ward-resident-forum",
    "title": "Hold regular ward resident forums",
    "quote": "Hold regular ward resident forums",
    "sector": "Education",
    "status": "Completed",
    "progress": 100,
    "target": "Hold six meetings with published minutes.",
    "officialSlugs": [
      "ward-6-councillor"
    ],
    "level": "Local",
    "leader": "Demo Ward 6 councillor",
    "location": "Ward 6, Port Harcourt City",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "ward-water-advocacy",
    "title": "Follow up on community water repairs",
    "quote": "Follow up on community water repairs",
    "sector": "Infrastructure",
    "status": "In Progress",
    "progress": 50,
    "target": "Submit three repair requests and track agency responses.",
    "officialSlugs": [
      "ward-6-councillor"
    ],
    "level": "Local",
    "leader": "Demo Ward 6 councillor",
    "location": "Ward 6, Port Harcourt City",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  },
  {
    "slug": "ward-health-monitoring",
    "title": "Report gaps in ward health services",
    "quote": "Report gaps in ward health services",
    "sector": "Healthcare",
    "status": "Not Started",
    "progress": 0,
    "target": "Complete a resident survey and present findings to the council.",
    "officialSlugs": [
      "ward-6-councillor"
    ],
    "level": "Local",
    "leader": "Demo Ward 6 councillor",
    "location": "Ward 6, Port Harcourt City",
    "source": "Simulated campaign scenario",
    "sourceUrl": "",
    "published": "Not a historical statement",
    "confidence": "Unrated",
    "updated": "2026-09-18",
    "origin": "simulated",
    "why": "Illustrative hackathon scenario. The commitment, target, status and progress are simulated, not a verified assessment of this office holder.",
    "projectSlugs": []
  }
];

